### ISSUE TITLE
Plot builder doesn't work

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1004]
Steps to reproduce
1. Open a table
2. Open sidebar
3. Create plot

Expected:
Plot opens

Actual:
Plot spins forever

```
dh-core.js:5157 Uncaught 
ClassCastException {stackTrace: null, backingJsObject: Error: java.lang.ClassCastException
    at ClassCastException.createError (http://localhost:4000/js…}
backingJsObject
: 
Error: java.lang.ClassCastException at ClassCastException.createError (http://localhost:4000/jsapi/dh-core.js:1192:10) at ClassCastException.initializeBackingError (http://localhost:4000/jsapi/dh-core.js:1212:46) at ClassCastException.Throwable (http://localhost:4000/jsapi/dh-core.js:1150:8) at ClassCastException.Exception (http://localhost:4000/jsapi/dh-core.js:1224:16) at ClassCastException.RuntimeException (http://localhost:4000/jsapi/dh-core.js:1241:16) at new ClassCastException (http://localhost:4000/jsapi/dh-core.js:1504:23) at Object.checkCriticalType_0 (http://localhost:4000/jsapi/dh-core.js:40664:16) at Object.$asInt (http://localhost:4000/jsapi/dh-core.js:40567:13) at Object.lambda$13_0 (http://localhost:4000/jsapi/dh-core.js:22850:16) at Function.copyTo_2 (http://localhost:4000/jsapi/dh-core.js:23255:11) at lambda (http://localhost:4000/jsapi/dh-core.js:152:22) at Object.$handleDelta (http://localhost:4000/jsapi/dh-core.js:22734:7) at Object.$handleDelta_0 (http://localhost:4000/jsapi/dh-core.js:23414:11) at Object.$lambda$78 (http://localhost:4000/jsapi/dh-core.js:10988:13) at Function.apply_36 (http://localhost:4000/jsapi/dh-core.js:12597:9) at lambda (http://localhost:4000/jsapi/dh-core.js:152:22) at Object.$lambda$15_2 (http://localhost:4000/jsapi/dh-core.js:30656:101) at Function.run_47 (http://localhost:4000/jsapi/dh-core.js:31300:9) at lambda (http://localhost:4000/jsapi/dh-core.js:152:22) at Function.onInvoke_211 (http://localhost:4000/jsapi/dh-core.js:29991:22) at lambda (http://localhost:4000/jsapi/dh-core.js:152:22)
__java$exception
: 
ClassCastException {stackTrace: null, backingJsObject: Error: java.lang.ClassCastException at ClassCastException.createError (http://localhost:4000/js…}
cause
: 
(...)
message
: 
"java.lang.ClassCastException"
stack
: 
"Error: java.lang.ClassCastException\n    at ClassCastException.createError (http://localhost:4000/jsapi/dh-core.js:1192:10)\n    at ClassCastException.initializeBackingError (http://localhost:4000/jsapi/dh-core.js:1212:46)\n    at ClassCastException.Throwable (http://localhost:4000/jsapi/dh-core.js:1150:8)\n    at ClassCastException.Exception (http://localhost:4000/jsapi/dh-core.js:1224:16)\n    at ClassCastException.RuntimeException (http://localhost:4000/jsapi/dh-core.js:1241:16)\n    at new ClassCastException (http://localhost:4000/jsapi/dh-core.js:1504:23)\n    at Object.checkCriticalType_0 (http://localhost:4000/jsapi/dh-core.js:40664:16)\n    at Object.$asInt (http://localhost:4000/jsapi/dh-core.js:40567:13)\n    at Object.lambda$13_0 (http://localhost:4000/jsapi/dh-core.js:22850:16)\n    at Function.copyTo_2 (http://localhost:4000/jsapi/dh-core.js:23255:11)\n    at lambda (http://localhost:4000/jsapi/dh-core.js:152:22)\n    at Object.$handleDelta (http://localhost:4000/jsapi/dh-core.js:22734:7)\n    at Object.$handleDelta_0 (http://localhost:4000/jsapi/dh-core.js:23414:11)\n    at Object.$lambda$78 (http://localhost:4000/jsapi/dh-core.js:10988:13)\n    at Function.apply_36 (http://localhost:4000/jsapi/dh-core.js:12597:9)\n    at lambda (http://localhost:4000/jsapi/dh-core.js:152:22)\n    at Object.$lambda$15_2 (http://localhost:4000/jsapi/dh-core.js:30656:101)\n    at Function.run_47 (http://localhost:4000/jsapi/dh-core.js:31300:9)\n    at lambda (http://localhost:4000/jsapi/dh-core.js:152:22)\n    at Function.onInvoke_211 (http://localhost:4000/jsapi/dh-core.js:29991:22)\n    at lambda (http://localhost:4000/jsapi/dh-core.js:152:22)"
suppressed
: 
(...)
get cause
: 
ƒ ()
get suppressed
: 
ƒ ()
[[Prototype]]
: 
Object
stackTrace
: 
null
[[Prototype]]
: 
Object
```

![plot](https://user-images.githubusercontent.com/1576283/211605632-1a0b9488-4a84-4da0-8c26-ea32bd4cc3c4.gif)

**Comment by mofojed** [comment]
@dsmmcken I'm unable to reproduce this using the following two tables:
```
from deephaven import empty_table
t = empty_table(1000).update(["x=i", "y=Math.sin(i)"])
```

```
from deephaven import time_table
tt = time_table("00:00:01").update(["y=Math.sin(i)"])
```

@dsmmcken what is the source table you used for this?

**Comment by dsmmcken** [comment]
```
from deephaven import empty_table, time_table

simple_ticking = time_table("00:00:01").update([
        "MyString=new String(`a`+i)",
        "MyInt=new Integer(i)",
        "MyLong=new Long(i)",
        "MyDouble=new Double(i+i/10)",
        "MyFloat=new Float(i+i/10)",
        "MyBoolean=new Boolean(i%2==0)",
        "MyChar= new Character((char) ((i%26)+97))",
        "MyShort=new Short(Integer.toString(i%32767))",
        "MyByte= new java.lang.Byte(Integer.toString(i%127))"])

complex_ticking = simple_ticking.update([
        "MyBigDecimal= new java.math.BigDecimal(i+i/10)",
        "MyBigInteger= new java.math.BigInteger(Integer.toString(i))"
])                          
```

I used timestamp and myint from complex ticking, and it is still reproducable, but interestingly your example tables are not.

**Comment by mofojed** [comment]
Interesting. Seems to be crashing because of the `MyBoolean` column. I've distilled it down to a simpler example:
```
from deephaven import time_table
tt = time_table("00:00:01").update(["y=i", "MyBoolean=new Boolean(i%2 ==0)"])
```
Couple things to note:
- Shouldn't crash if there's a boolean
- Shouldn't be getting the boolean in the snapshot anyway since it's not part of the figure I created at all.
