### ISSUE TITLE
Update JSZip

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1080]
We are pinned to 3.2.2 of JSZip that has nodestream support, as it was removed: https://github.com/Stuk/jszip/issues/663

Making a ticket to update the version and track this issue. Previously Dependabot opened a PR: https://github.com/deephaven/web-client-ui/pull/183

**Comment by mofojed** [comment]
Tried updating to latest v3.10.1, still failing with error:
```
[CsvInputBar] Error: nodestream is not supported by this platform
    at a.checkSupport (jszip.min.js:13:34660)
    at f.toNodejsStream (jszip.min.js:13:27913)
    at n.nodeStream (jszip.min.js:13:45595)
    at CsvTypeParser.parse (CsvTypeParser.ts:221:36)
    at _CsvParser.parse (CsvParser.ts:192:16)
    at CsvInputBar.handleFile (CsvInputBar.tsx:220:12)
    at CsvInputBar.tsx:245:18
```

**Comment by mattrunyon** [comment]
Should we be using `nodestream` even? It might be the older stream type where they bundled the Node built-in into the browser, but browsers have been making progress on having native streams
