### ISSUE TITLE
Unable to "filter by value" -> "is equal to" on bigdecimal/bigint

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#1354]
**Description**

Using the following table attempting to right click, filter by value equals on big decimal or big int doesn't work.

```
from deephaven import empty_table

size = 100
scale = 1000

random_values_with_null_NaN = empty_table(size).update([
    "MyString=(i%11==0? i%2==0 ? i%3==0? `null` : `` :  null : `a`+(int)(scale*(Math.random()*2-1)))",
    "MyInt=(i%12==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyLong=(i%13==0 ? null : (long)(scale*(Math.random()*2-1)))",
    "MyFloat=(float)(i%14==0 ? null : i%10==0 ? 1.0F/0.0F: i%5==0 ? -1.0F/0.0F : (float) scale*(Math.random()*2-1))",
    "MyDouble=(double)(i%16==0 ? null : i%10==0 ? 1.0D/0.0D: i%5==0 ? -1.0D/0.0D : (double) scale*(Math.random()*2-1))",
    "MyBoolean = (i%17==0 ? null : (int)(10*Math.random())%2==0)",
    "MyChar = (i%18==0 ? null : new Character((char) (((26*Math.random())%26)+97)) )",
    "MyShort=(short)(i%19==0 ? null : (int)(scale*(Math.random()*2-1)))",
    "MyByte=(Byte)(i%19==0 ? null : new Byte( Integer.toString((int)(Byte.MAX_VALUE*(Math.random()*2-1)))))",
    "MyBigDecimal=(i%21==0 ? null : new java.math.BigDecimal(scale*(Math.random()*2-1)))",
    "MyBigInteger=(i%22==0 ? null : new java.math.BigInteger(Integer.toString((int)(scale*(Math.random()*2-1)))))"
])
```

**Steps to reproduce**

1. Run the above code
2. Right click on a value from the MyBigDecimal or MyBigInteger column
3. Select "Filter by value" then select "is equal to" from the menu

**Expected results**

Table is filtered

**Actual results**

Filter is not applied. Less than or greater than filters do work.

```
heduler-Concurrent-4 | i.d.s.s.SessionState      | Internal Error 'fcd7bdef-5d7d-4485-8699-3f51cc52d555' java.lang.IllegalArgumentException: Unknown type java.math.BigInteger for MatchFilter value auto-conversion
        at io.deephaven.engine.table.impl.select.MatchFilter$ColumnTypeConvertorFactory.getConvertor(MatchFilter.java:396)
        at io.deephaven.engine.table.impl.select.MatchFilter.init(MatchFilter.java:133)
        at io.deephaven.engine.table.impl.QueryTable.lambda$whereInternal$29(QueryTable.java:1140)
        at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:519)
        at io.deephaven.engine.table.impl.QueryTable.whereInternal(QueryTable.java:1108)
        at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:1096)
        at io.deephaven.engine.table.impl.QueryTable.where(QueryTable.java:109)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:57)
        at io.deephaven.server.table.ops.FilterTableGrpcImpl.create(FilterTableGrpcImpl.java:30)
        at io.deephaven.server.table.ops.TableServiceGrpcImpl$BatchExportBuilder.doExport(TableServiceGrpcImpl.java:689)
        at io.deephaven.server.table.ops.TableServiceGrpcImpl.lambda$batch$5(TableServiceGrpcImpl.java:541)
        at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:897)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.deephaven.server.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:174)
        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.server.console.python.DebuggingInitializer.lambda$createInitializer$0(DebuggingInitializer.java:30)
        at java.lang.Thread.run(Thread.java:833)
```

**Versions**

Engine Version: 0.26.0
Web UI Version: 0.40.4
Java Version: 17.0.7
Barrage Version: 0.5.0

**Comment by dsmmcken** [comment]
Closing as duplicate
