### ISSUE TITLE
Cannot add Control from Controls menu with click

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1362]
**Description**

When you click an item from the Controls list, it should open in the dashboard. Currently it just throws an exception, and you have to click and drag the item on the dashboard.

**Steps to reproduce**
1. Open the controls list and click an item (such as Input Filter)

**Expected results**
1. The control should open

**Actual results**
1. The control does not open, and there is an error in the logs

**Additional details and attachments**
```
caught TypeError: Cannot read properties of null (reading 'preventDefault')
    at GC.onMouseDown (DragListener.ts:63:12)
    at Yh._createDragListener (DragSourceFromEvent.ts:49:24)
    at new Yh (DragSourceFromEvent.ts:29:10)
    at Qh.createDragSourceFromEvent (LayoutManager.ts:661:12)
    at $.openComponent (LayoutUtils.ts:482:27)
    at Object.<anonymous> (MarkdownPlugin.tsx:79:19)
    at qC.emit (EventEmitter.ts:68:20)
    at Si.emitLayoutEvent (AppMainContainer.tsx:363:33)
    at Si.handleControlSelect (AppMainContainer.tsx:406:14)
    at action (AppControlsMenu.tsx:173:31)
    at C (AppControlsMenu.tsx:102:14)
    at Object.Pne (react-dom.production.min.js:52:317)
    at Mne (react-dom.production.min.js:52:471)
    at Nne (react-dom.production.min.js:53:35)
    at AN (react-dom.production.min.js:100:68)
    at gH (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Vq (react-dom.production.min.js:292:189)
    at Dne (react-dom.production.min.js:50:57)
    at bH (react-dom.production.min.js:105:469)
    at MD (react-dom.production.min.js:75:265)
    at $D (react-dom.production.min.js:74:124)
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Hh (react-dom.production.min.js:122:325)
    at Gq (react-dom.production.min.js:292:48)
    at Kne (react-dom.production.min.js:73:352)
o
```

**Versions**
Engine Version: 0.26.0
Web UI Version: 0.40.4
Java Version: 11.0.19
Barrage Version: 0.5.0

**Comment by dsmmcken** [comment]
looking, probably caused by me.
