### ISSUE TITLE
Unable to import zipped CSV file

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1416]
**Description**

Looks like we broke uploading zipped CSV files at some point.

**Steps to reproduce**
1. Drag and drop a zipped CSV file into the console (attached below) and click "Upload"

**Expected results**
1. CSV uploads, table opens

**Actual results**
1. Fails to upload. No error displayed to user. Error in the console logs is:
```
[CsvInputBar] Error: nodestream is not supported by this platform
    at e.checkSupport (utils.js:352:15)
    at Kte.toNodejsStream (StreamHelper.js:196:15)
    at LM.nodeStream (zipObject.js:85:58)
    at Kt.parse (CsvTypeParser.js:165:42)
    at oo.parse (CsvParser.js:124:16)
    at lp.handleFile (CsvInputBar.js:184:12)
    at CsvInputBar.js:209:16
```

**Additional details and attachments**
[table-2023-07-21-110601.zip](https://github.com/deephaven/web-client-ui/files/12130035/table-2023-07-21-110601.zip)

**Versions**

```
Engine Version: 0.27.0
Web UI Version: 0.44.1
Java Version: 11.0.19
Barrage Version: 0.6.0
```

**Comment by mofojed** [comment]
May update JSZip at the same time: #1080
