### ISSUE TITLE
Cannot import CSV, get a `Can't parse LOCAL_TIME` exception in the logs, no error shown

### ISSUE THREAD

**Issue by mofojed** [deephaven/web-client-ui#1432]
**Description**

Attempting to import a CSV with a timestamp is resulting in an error that is not displayed to the user

**Steps to reproduce**
1. Import the attached CSV using the UI:
[table-2023-06-07-103446-one-row-timestamp-only.csv](https://github.com/deephaven/web-client-ui/files/12233725/table-2023-06-07-103446-one-row-timestamp-only.csv)

**Expected results**
1. CSV should be imported into a table and displayed

**Actual results**
1. Nothing happens. An error is shown in the browser log.
```
Error: java.lang.UnsupportedOperationException: Can't parse LOCAL_TIME
    at UnsupportedOperationException_0.createError (dh-core.js:1217:10)
    at UnsupportedOperationException_0.initializeBackingError (dh-core.js:1237:46)
    at UnsupportedOperationException_0.Throwable_0 (dh-core.js:1182:8)
    at UnsupportedOperationException_0.Exception_1 (dh-core.js:1261:18)
    at UnsupportedOperationException_0.RuntimeException_1 (dh-core.js:1274:18)
    at new UnsupportedOperationException_0 (dh-core.js:2158:25)
    at JsDataHandler$14.write_1 [as write_0] (dh-core.js:22773:14)
    at Object.$lambda$74_0 (dh-core.js:14745:94)
    at WorkerConnection$lambda$74$Type.fetch_22 [as fetch_1] (dh-core.js:16690:9)
    at Object.$lambda$32_1 (dh-core.js:34137:23)
    at ClientTableState$lambda$32$Type.accept_87 [as accept] (dh-core.js:34858:9)
    at Function.onInvoke_2 (dh-core.js:7825:12)
    at lambda (dh-core.js:173:22)
    at new Promise (<anonymous>)
    at Object.$refetch_1 (dh-core.js:34258:13)
    at Object.$newState (dh-core.js:14883:16)
    at Object.$newTable (dh-core.js:14908:16)
    at IdeSession.newTable (dh-core.js:33048:16)
    at oo.handleCreateTable (CsvParser.js:207:13)
    at oo.handleChunk (CsvParser.js:160:9)
    at h.parseChunk (papaparse.min.js:7:6346)
    at h._chunkLoaded (papaparse.min.js:7:9318)
    at FileReader.<anonymous> (papaparse.min.js:7:18166)
```

**Versions**

Engine Version: 0.27.0
Web UI Version: 0.45.0
Java Version: 11.0.20
Barrage Version: 0.6.0

**Comment by mofojed** [comment]
Not showing an error is also a problem in #1416.

**Comment by mofojed** [comment]
To actually support importing as a timestamp, we need https://github.com/deephaven/deephaven-core/issues/1041
As a stopgap though, we should at least show the error to the user.
