### ISSUE TITLE
Latest version (0.10.0) not working on WSL

### ISSUE THREAD

**Issue by jakemulf** [deephaven/web-client-ui#477]
**Description**

Launching Deephaven on the latest version (0.10.0 as of writing) causes the following errors to show in the browser logs. This only occurs on WSL, not OSX

```
:10000/js-plugins/manifest.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
LogProxy.ts:82 [AppInit] Unable to load plugins: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (main.265e4f7b.chunk.js:1:1235669)
isEnabled.console.error @ LogProxy.ts:82
LogProxy.ts:72 [LocalWorkspaceStorage] Unable to load workspace data, initializing to default data
LogProxy.ts:72 [SessionUtils] Starting connection to 'http://localhost:10000/'...
LogProxy.ts:72 [SessionUtils] Getting console types...
LogProxy.ts:82 [DownloadServiceWorkerUtils] Failed to register service worker TypeError: Failed to register a ServiceWorker for scope ('http://localhost:10000/idedownload/') with script ('http://localhost:10000/idedownload/serviceWorker.js'): A bad HTTP response code (404) was received when fetching the script.
isEnabled.console.error @ LogProxy.ts:82
LogProxy.ts:72 [SessionUtils] Available types: Array(1)
LogProxy.ts:72 [SessionUtils] Starting session with type python
LogProxy.ts:72 [SessionUtils] Console session established Object
dh-internal.js:1 WebSocket connection to 'ws://localhost:10000/io.deephaven.proto.backplane.grpc.ApplicationService/ListFields' failed: WebSocket is closed before the connection is established.
cancel @ dh-internal.js:1
LogProxy.ts:82 TypeError: Cannot destructure property 'metadata' of 'e' as it is undefined.
    at ew.hydrateDefault (main.265e4f7b.chunk.js:1:1243032)
    at main.265e4f7b.chunk.js:1:342933
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327638)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at main.265e4f7b.chunk.js:1:344004
    at Fl (4.241fc996.chunk.js:2:4161537)
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Pl (4.241fc996.chunk.js:2:4160998)
    at yl (4.241fc996.chunk.js:2:4152488)
    at 4.241fc996.chunk.js:2:4102079
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Yr (4.241fc996.chunk.js:2:4102024)
    at $r (4.241fc996.chunk.js:2:4101959)
    at _l (4.241fc996.chunk.js:2:4152906)
    at Object.notify (4.241fc996.chunk.js:2:456996)
    at Object.notifyNestedSubs (4.241fc996.chunk.js:2:457593)
    at r (4.241fc996.chunk.js:2:457427)
    at v (4.241fc996.chunk.js:2:1528009)
    at 4.241fc996.chunk.js:2:3938308
    at main.265e4f7b.chunk.js:1:38855
    at main.265e4f7b.chunk.js:1:38741
    at n.<computed> (4.241fc996.chunk.js:2:462884)
    at main.265e4f7b.chunk.js:1:1257095
isEnabled.console.error @ LogProxy.ts:82
LogProxy.ts:82 [redux-crashReporter] Error executing Object  with state  Object : TypeError: Cannot destructure property 'metadata' of 'e' as it is undefined.
    at ew.hydrateDefault (main.265e4f7b.chunk.js:1:1243032)
    at main.265e4f7b.chunk.js:1:342933
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327638)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at main.265e4f7b.chunk.js:1:344004
    at Fl (4.241fc996.chunk.js:2:4161537)
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Pl (4.241fc996.chunk.js:2:4160998)
    at yl (4.241fc996.chunk.js:2:4152488)
    at 4.241fc996.chunk.js:2:4102079
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Yr (4.241fc996.chunk.js:2:4102024)
    at $r (4.241fc996.chunk.js:2:4101959)
    at _l (4.241fc996.chunk.js:2:4152906)
    at Object.notify (4.241fc996.chunk.js:2:456996)
    at Object.notifyNestedSubs (4.241fc996.chunk.js:2:457593)
    at r (4.241fc996.chunk.js:2:457427)
    at v (4.241fc996.chunk.js:2:1528009)
    at 4.241fc996.chunk.js:2:3938308
    at main.265e4f7b.chunk.js:1:38855
    at main.265e4f7b.chunk.js:1:38741
    at n.<computed> (4.241fc996.chunk.js:2:462884)
    at main.265e4f7b.chunk.js:1:1257095
isEnabled.console.error @ LogProxy.ts:82
LogProxy.ts:82 [AppInit] TypeError: Cannot destructure property 'metadata' of 'e' as it is undefined.
    at ew.hydrateDefault (main.265e4f7b.chunk.js:1:1243032)
    at main.265e4f7b.chunk.js:1:342933
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327638)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at Function.hydrateLayoutConfig (main.265e4f7b.chunk.js:1:327668)
    at main.265e4f7b.chunk.js:1:344004
    at Fl (4.241fc996.chunk.js:2:4161537)
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Pl (4.241fc996.chunk.js:2:4160998)
    at yl (4.241fc996.chunk.js:2:4152488)
    at 4.241fc996.chunk.js:2:4102079
    at t.unstable_runWithPriority (4.241fc996.chunk.js:2:4179314)
    at Kr (4.241fc996.chunk.js:2:4101856)
    at Yr (4.241fc996.chunk.js:2:4102024)
    at $r (4.241fc996.chunk.js:2:4101959)
    at _l (4.241fc996.chunk.js:2:4152906)
    at Object.notify (4.241fc996.chunk.js:2:456996)
    at Object.notifyNestedSubs (4.241fc996.chunk.js:2:457593)
    at r (4.241fc996.chunk.js:2:457427)
    at v (4.241fc996.chunk.js:2:1528009)
    at 4.241fc996.chunk.js:2:3938308
    at main.265e4f7b.chunk.js:1:38855
    at main.265e4f7b.chunk.js:1:38741
    at n.<computed> (4.241fc996.chunk.js:2:462884)
    at main.265e4f7b.chunk.js:1:1257095
```

**Steps to reproduce**

Launch Deephaven version 0.10.0

**Expected results**

Deephaven launches properly

**Actual results**

The UI doesn't load and the errors are displayed in the browser console

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**
 - Deephaven: 0.10.0
 - OS: Windows WSL
 - Browser: Chrome/Firefox
 - Docker: Docker version 20.10.12, build e91ed57

**Comment by mofojed** [comment]
It's falling back to the default layout and failing to hydrate.
