### ISSUE TITLE
Unable to open Advanced Filter dialog

### ISSUE THREAD

**Issue by vbabich** [deephaven/web-client-ui#648]
**Description**

The app throws an exception when trying to open Advanced Filter on a table column.

**Steps to reproduce**
1. Run this command in the console to create a table:
```
from deephaven.TableTools import emptyTable
t = emptyTable(10).update("x = i")
```
2. Click on any value in the `x` column to focus the table.
3. Press `Cmd+F` to show the filter bar, click on the Funnel icon to open the Advanced filter dialog:
![Screen Shot 2022-07-12 at 10 16 47 AM](https://user-images.githubusercontent.com/2853653/178542451-af8b397d-d251-4c0b-81a7-da6e98c105f5.png)

**Expected results**

Advanced filter dialog shows up.

**Actual results**

The Advanced Filter dialog doesn't show up, the app throws an exception in the browser console:
```
AdvancedFilterCreator.tsx:129 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at new AdvancedFilterCreator (AdvancedFilterCreator.tsx:129:1)
    at constructClassInstance (react-dom.development.js:12716:1)
    at updateClassComponent (react-dom.development.js:17425:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push.../../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at Popper.initPopper (Popper.tsx:178:1)
    at Popper.show (Popper.tsx:204:1)
    at Popper.tsx:106:1
```

**Versions**
 - Deephaven: 0.14.1

**Comment by dsmmcken** [comment]
Typescript broke more than just not appearing, fixing sub-breakages.
