### ISSUE TITLE
Copy Cell/Copy Cell Unformatted not working

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#660]
The "Copy Cell" and "Copy Cell Unformatted" actions are not working for me in DHC Version 0.14.1. Have tried with String, long, and int columns.

I get this error when I right-click on a cell (`long`) of a Table and click "Copy Cell":

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at Function.value (ContextActionUtils.ts:119:32)
    at n.value (IrisGrid.tsx:1782:26)
    at Object.action (IrisGridContextMenuHandler.tsx:523:22)
    at n.value (ContextMenu.tsx:506:18)
    at onClick (ContextMenuItem.tsx:22:25)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Er (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Pe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Qt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
```

and this from "Copy Cell Unformatted" (only difference is IrisGridContextMenuHandler line number):

```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at Function.value (ContextActionUtils.ts:119:32)
    at n.value (IrisGrid.tsx:1782:26)
    at Object.action (IrisGridContextMenuHandler.tsx:532:22)
    at n.value (ContextMenu.tsx:506:18)
    at onClick (ContextMenuItem.tsx:22:25)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Er (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Pe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Qt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
```

**Comment by dsmmcken** [comment]
@rbasralian can you confirm browser/os this error occurred on?

**Comment by rbasralian** [comment]
Chrome. Version 103.0.5060.134 (Official Build) (x86_64)

macOS 12.5

DH image is ghcr.io/deephaven/server-pytorch:latest (running here on VPN http://10.40.0.54:30100/ide/ if you want to try it)

**Comment by mofojed** [comment]
I'm able to reproduce through VPN, and am able to reproduce in Chrome `103.0.5060.114 (Official Build) (arm64)`. Thanks @rbasralian !

I'll verify Tony's fix and then we can close
