### ISSUE TITLE
Can't create links in 0.15.2

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#701]
In 0.15.2, hitting cmd+L to enter "link mode" works more reliably than 0.14, but I can't actually create any links. Even though the cursor changes to the link icon and I get the dialog in the lower-right corner of the screen, clicking on a column (either the column data or the headers) doesn't let me start drawing a link

DH images v0.15.0, Chrome 103.0.5060.134 (Official Build) (x86_64)

Can test by running this and trying to link Col1:

```python
from deephaven import empty_table
t1 = empty_table(100).update_view('Col1 = ii')
t2 = t1.update_view('Col2 = Col1 * Col1').sum_by('Col1')
```

**Comment by mofojed** [comment]
There's an error in the console logs:
```
[LinkerOverlayContent] Unable to get point for link Object Error: Unable to find panel container for id: o1cbGaWyL
    at n.value (LinkerOverlayContent.tsx:103:13)
    at LinkerOverlayContent.tsx:137:31
    at Array.map (<anonymous>)
    at n.value (LinkerOverlayContent.tsx:134:8)
    at Ka (react-dom.production.min.js:187:188)
    at qa (react-dom.production.min.js:186:173)
    at $s (react-dom.production.min.js:269:427)
    at Ll (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at jl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Yi (react-dom.production.min.js:123:61)
    at $i (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at v.setState (react.production.min.js:12:369)
    at n.value (IrisGrid.tsx:2715:10)
    at n.value (Grid.tsx:764:5)
    at Grid.tsx:756:12
```

This is a regression and will require a hotfix on the latest Community release.

**Comment by SparkyFnay** [comment]
This bug is fixed as of 0.15.3 with the merge of PR #697

**Comment by dsmmcken** [comment]
Link the issue from the PR then it auto closes when merged.

**Comment by mofojed** [comment]
@dsmmcken That PR is a different issue. He already linked it with the correct PR which has already been merged.

**Comment by dsmmcken** [comment]
my bad, saw them in the feed and thought they were the same but not linked.
