### ISSUE TITLE
Deephaven context menu doesn't work on DateTime columns

### ISSUE THREAD

**Issue by rbasralian** [deephaven/web-client-ui#725]
When I right-click on DateTime column headers, I get the browser’s default context menu instead of the Deephaven UI’s. This happens in both Safari and Chrome.

In Chrome I have this error in the logs when I right-click:

```
Uncaught Error: Value is null or undefined
    at F (Asserts.ts:5:28)
    at n.value (IrisGridContextMenuHandler.tsx:727:5)
    at n.value (IrisGridContextMenuHandler.tsx:360:23)
    at n.value (IrisGridContextMenuHandler.tsx:662:30)
    at n.value (Grid.tsx:1628:24)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Er (react-dom.production.min.js:100:68)
    at Tr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Pe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Qt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
```

Right-clicking on DateTime column:
![image](https://user-images.githubusercontent.com/9516585/185710971-1209788a-418a-409d-9409-30143ee32354.png)

Right-clicking on any other column:

![image](https://user-images.githubusercontent.com/9516585/185711198-1bf28d1e-f7f7-4f67-9bc9-30e813bee983.png)

This is with version Version 0.15.4.

Can reproduce it quickly with this script:

```
from deephaven import empty_table

t = empty_table(100).update([
    'Int = i',
    'Long = ii',
    'Char = (char) ((ii % 26) + 65)',
    'Double = (double) ii',
    'Str = String.valueOf(Char) + Char + Char + Char',
    'DateTime=currentTime()'
])
```

(available under the panels menu here on VPN http://datetime-bug-test.devrel.lab.deephaven.io/ide/)

**Comment by vbabich** [comment]
Duplicates #647
