### ISSUE TITLE
initial load errors with cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#733]
Guessing this happened with the typescript conversion of dashboard containers.

Steps to reproduce: create a new incognito window and visit the console. Only happens with a new window/first load.

```
LogProxy.ts:82 TypeError: Cannot read properties of undefined (reading 'config')
    at n.value (ConsolePanel.jsx:275:13)
    at Ka (react-dom.production.min.js:187:188)
    at qa (react-dom.production.min.js:186:173)
    at $s (react-dom.production.min.js:269:427)
    at Ll (react-dom.production.min.js:250:347)
    at El (react-dom.production.min.js:250:278)
    at jl (react-dom.production.min.js:250:138)
    at yl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ki (react-dom.production.min.js:122:325)
    at Yi (react-dom.production.min.js:123:61)
    at $i (react-dom.production.min.js:122:428)
    at _l (react-dom.production.min.js:244:190)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at i (Subscription.js:90:20)
    at m (redux.js:296:32)
    at index.js:20:16
    at crashReporter.ts:8:12
    at logger.ts:8:18
    at n.<computed> (bindActionCreators.js:9:16)
    at AppInit.jsx:184:7
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
isEnabled.console.error @ LogProxy.ts:82
17:01:35.076 LogProxy.ts:82 [PanelManager] updatePanel Panel did not have an ID n
isEnabled.console.error @ LogProxy.ts:82
17:01:35.077 LogProxy.ts:82 [PanelManager] updatePanel Panel did not have an ID n
isEnabled.console.error @ LogProxy.ts:82
17:01:35.079 LogProxy.ts:82 [PanelManager] updatePanel Panel did not have an ID n
isEnabled.console.error @ LogProxy.ts:82
17:01:35.083 DashboardUtils.ts:17 Uncaught TypeError: Cannot read properties of undefined (reading 'metadata')
    at Wi (DashboardUtils.ts:17:11)
    at DashboardLayout.tsx:150:50
    at Function.value (LayoutUtils.ts:285:37)
    at Function.value (LayoutUtils.ts:296:32)
    at Function.value (LayoutUtils.ts:296:32)
    at Function.value (LayoutUtils.ts:296:32)
    at Object.<anonymous> (DashboardLayout.tsx:187:48)
    at r.LayoutManager.emit (goldenlayout.js:265:20)
    at r.items.Root._propagateEventToLayoutManager (goldenlayout.js:4520:24)
    at goldenlayout.js:91:5
  ```

**Comment by mofojed** [comment]
@dsmmcken What version is this on? I can't reproduce this on v0.15.6.
Possibly already fixed with https://github.com/deephaven/web-client-ui/pull/697 ?

**Comment by dsmmcken** [comment]
Wasn't on latest, looks like it is actually fixed now. I don't know what version I was running prior.
