### ISSUE TITLE
TableAnimation cannot pickle Java arrays

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/web-client-ui#891]
**Description**

When trying to use TableAnimation from Python to animate a matplotlib figure using code from the docs (or equivalent code), the following error gets thrown:

```
Value: cannot pickle '[I' object
```

In the case above, I was trying to plot integer values. When trying to plot double values, the error mentions a `[D` object.

**Steps to reproduce**

Run the following code (found in https://deephaven.io/core/docs/how-to-guides/plotting/matplot/#matplotlib-examples-with-tableanimation):

```python
import matplotlib.pyplot as plt
from deephaven import time_table
from deephaven.plugin.matplotlib import TableAnimation

# Create a ticking table with the sin function
tt = time_table("00:00:01").update(["x=i", "y=Math.sin(x)"])

fig = plt.figure()      # Create a new figure
ax = fig.subplots()     # Add an axes to the figure
line, = ax.plot([],[])  # Plot a line. Start with empty data, will get updated with table updates.

# Define our update function. We only look at `data` here as the data is already stored in the format we want
def update_fig(data, update):
    line.set_data([data['x'], data['y']])
    
    # Resize and scale the axes. Our data may have expanded and we don't want it to appear off screen.
    ax.relim()
    ax.autoscale_view(True, True, True)

# Create our animation. It will listen for updates on `tt` and call `update_fig` whenever there is an update
ani = TableAnimation(fig, tt, update_fig)
```

**Expected results**

The figure to animate with a line updating in real-time.

**Actual results**

The following two errors:

```
ERROR EFAULT.refreshThread | rumentedTableListenerBase | Uncaught exception for entry= Uninstrumented code, added.size()=1, modified.size()=0, removed.size()=0, shifted.size()=0, modifiedColumnSet={}:
java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: cannot pickle '[I' object
Line: 92
Namespace: copy
File: /usr/lib/python3.10/copy.py
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table_listener.py", line 284, in wrapper
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 74, in _on_table_update
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 154, in _step
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/animation.py", line 1097, in _step
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/animation.py", line 1116, in _draw_next_frame
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 160, in _draw_frame
  File "<string>", line 14, in update_fig
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/lines.py", line 650, in set_data
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/lines.py", line 1279, in set_xdata
  File "/usr/lib/python3.10/copy.py", line 92, in copy

        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.integrations.python.PythonReplayListenerAdapter.onUpdate(PythonReplayListenerAdapter.java:88)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:294)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:272)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1459)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1177)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1122)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1736)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1726)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1713)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1567)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:276)
16:02:37.981 ERROR EFAULT.refreshThread | .AsyncClientErrorNotifier | Error in table update: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: cannot pickle '[I' object
Line: 92
Namespace: copy
File: /usr/lib/python3.10/copy.py
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/table_listener.py", line 284, in wrapper
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 74, in _on_table_update
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 154, in _step
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/animation.py", line 1097, in _step
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/animation.py", line 1116, in _draw_next_frame
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/matplotlib/__init__.py", line 160, in _draw_frame
  File "<string>", line 14, in update_fig
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/lines.py", line 650, in set_data
  File "/opt/deephaven/venv/lib/python3.10/site-packages/matplotlib/lines.py", line 1279, in set_xdata
  File "/usr/lib/python3.10/copy.py", line 92, in copy

        at org.jpy.PyLib.callAndReturnObject(PyLib.java:-2)
        at org.jpy.PyObject.call(PyObject.java:449)
        at io.deephaven.integrations.python.PythonReplayListenerAdapter.onUpdate(PythonReplayListenerAdapter.java:88)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.lambda$run$0(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRunInternal(InstrumentedTableListenerBase.java:294)
        at io.deephaven.engine.table.impl.InstrumentedTableListenerBase$NotificationBase.doRun(InstrumentedTableListenerBase.java:272)
        at io.deephaven.engine.table.impl.InstrumentedTableUpdateListener$Notification.run(InstrumentedTableUpdateListener.java:37)
        at io.deephaven.engine.updategraph.NotificationQueue$Notification.runInContext(NotificationQueue.java:60)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.runNotification(UpdateGraphProcessor.java:1298)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$QueueNotificationProcessor.doWork(UpdateGraphProcessor.java:1459)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNormalNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1177)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.flushNotificationsAndCompleteCycle(UpdateGraphProcessor.java:1122)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.lambda$doRefresh$10(UpdateGraphProcessor.java:1736)
        at io.deephaven.util.locks.FunctionalLock.doLocked(FunctionalLock.java:31)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.doRefresh(UpdateGraphProcessor.java:1726)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshAllTables(UpdateGraphProcessor.java:1713)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor.refreshTablesAndFlushNotifications(UpdateGraphProcessor.java:1567)
        at io.deephaven.engine.updategraph.UpdateGraphProcessor$1.run(UpdateGraphProcessor.java:276)
```

**Additional details and attachments**

If applicable, add any additional screenshots, logs, or other attachments to help explain your problem.

**Versions**

 - Deephaven: 0.18.0
 - OS: OS X Monterey 12.3.1
 - Browser: Chrome
 - Docker: 20.10.13

**Comment by mofojed** [comment]
Fixed with https://github.com/deephaven/deephaven-plugin-matplotlib/pull/11
