### ISSUE TITLE
Attempting to close a non-python file in a python session crashes app entirely

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/web-client-ui#969]
**Description**

The whole app crashes and app level error boundary displays:
"Unable to connect: Unknown Error"

Error in server logs from Jedi autocomplete.

```
core-server-1  | 2022-12-20T16:59:02.293Z | qtp254918854-31      |  INFO | .c.ConsoleServiceGrpcImpl | Using jedi for python autocomplete
core-server-1  | 2022-12-20T16:59:03.789Z | qtp254918854-29      | ERROR | ntrantCallsDirectExecutor | Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@3b219785
core-server-1  | org.jpy.KeyError: Error in Python interpreter:
core-server-1  | Type: <class 'KeyError'>
core-server-1  | Value: 'inmemory://model/5'
core-server-1  | Line: 59
core-server-1  | Namespace: close_doc
core-server-1  | File: /opt/deephaven-venv/lib/python3.7/site-packages/deephaven_internal/auto_completer/_completer.py
core-server-1  | Traceback (most recent call last):
core-server-1  |   File "/opt/deephaven-venv/lib/python3.7/site-packages/deephaven_internal/auto_completer/_completer.py", line 59, in close_doc
core-server-1  |
core-server-1  |        at org.jpy.PyLib.callAndReturnObject(Native Method)
core-server-1  |        at org.jpy.PyObject.callMethod(PyObject.java:432)
core-server-1  |        at io.deephaven.server.console.completer.PythonAutoCompleteObserver.onNext(PythonAutoCompleteObserver.java:89)
core-server-1  |        at io.deephaven.server.console.completer.PythonAutoCompleteObserver.onNext(PythonAutoCompleteObserver.java:27)
core-server-1  |        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
core-server-1  |        at io.grpc.ForwardingServerCallListener.onMessage(ForwardingServerCallListener.java:33)
core-server-1  |        at io.grpc.Contexts$ContextualizedServerCallListener.onMessage(Contexts.java:76)
core-server-1  |        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333)
core-server-1  |        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316)
core-server-1  |        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835)
core-server-1  |        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
core-server-1  |        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
core-server-1  |        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:846)
core-server-1  |        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:182)
core-server-1  |        at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:413)
core-server-1  |        at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:276)
core-server-1  |        at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
core-server-1  |        at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
core-server-1  |        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
core-server-1  |        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
core-server-1  |        at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
core-server-1  |        at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:218)
core-server-1  |        at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
core-server-1  |        at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
core-server-1  |        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1465)
core-server-1  |        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1484)
core-server-1  |        at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
core-server-1  |        at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
core-server-1  |        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
core-server-1  |        at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:350)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
core-server-1  |        at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
core-server-1  |        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
core-server-1  |        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
core-server-1  |        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
core-server-1  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
core-server-1  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
core-server-1  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
core-server-1  |        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
core-server-1  |        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
core-server-1  |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
core-server-1  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
core-server-1  |        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Steps to reproduce**
1. Start python docker session
2. In the code studio's file explorer UI create a new file
3. Rename it something like "myfile.groovy" or "myfile.test"
4. Save the file.
5. Close the file.

**Expected results**

File is closed.

**Actual results**

Entire app crashes. 

You can page refresh and it'll be okay though.

**Versions**

Engine Version: 0.20.0
Web UI Version: 0.23.0
Java Version: 11.0.16
Barrage Version: 0.5.0

**Comment by dsmmcken** [comment]
Not sure if this belongs here or in deephaven-core, or if it is owned by @JamesXNelson or @mofojed. Please triage to the right repo.

**Comment by mofojed** [comment]
UI is calling `closeDocument` but not calling `openDocument` (since there's no active session). We shouldn't call closeDocument if we never opened the doc in the first place, so I'll put in a fix for that.
That being said, it probably shouldn't kill the whole connection if there's an error thrown either. Should have some more protection on the server for that.

**Comment by dsmmcken** [comment]
> That being said, it probably shouldn't kill the whole connection if there's an error thrown either. Should have some more protection on the server for that.

Follow-up: core ticket for that?
